ServerEvents.recipes(event => {
    event.recipes.gtceu.assembly_line("smd_quant_1")
    .itemInputs("4x gtceu:advanced_smd_transistor","8x gtceu:zephyrite_foil","16x gtceu:fine_aerogem_wire")
    .itemOutputs("kubejs:quant_chip_1")
    .inputFluids([Fluid.of("gtceu:polycaprolactam",1440),Fluid.of("gtceu:tungsten_carbide",500),Fluid.of("gtceu:iridium",250)])
    .duration(280)
    .EUt(GTValues.VA[GTValues.LuV])
    ["scannerResearch(java.util.function.UnaryOperator)"](b => b.researchStack(Item.of('gtceu:advanced_smd_transistor')).EUt(GTValues.VA[GTValues.IV]).duration(420))

    event.recipes.gtceu.assembly_line("smd_quant_2")
    .itemInputs("4x gtceu:advanced_smd_inductor","8x gtceu:aerogem_foil","16x gtceu:fine_aerogem_wire")
    .itemOutputs("kubejs:quant_chip_2")
    .inputFluids([Fluid.of("gtceu:polycaprolactam",1440),Fluid.of("gtceu:tungsten_carbide",500),Fluid.of("gtceu:iridium",250)])
    .duration(280)
    .EUt(GTValues.VA[GTValues.LuV])
    ["scannerResearch(java.util.function.UnaryOperator)"](b => b.researchStack(Item.of('gtceu:advanced_smd_inductor')).EUt(GTValues.VA[GTValues.IV]).duration(420))

    event.recipes.gtceu.assembly_line("smd_quant_3")
    .itemInputs("4x gtceu:advanced_smd_resistor","2x gtceu:dense_cloudiron_plate","32x gtceu:fine_nimbusite_wire")
    .itemOutputs("kubejs:quant_chip_3")
    .inputFluids([Fluid.of("gtceu:polycaprolactam",1440),Fluid.of("gtceu:tungsten_carbide",500),Fluid.of("gtceu:iridium",250)])
    .duration(280)
    .EUt(GTValues.VA[GTValues.LuV])
    ["scannerResearch(java.util.function.UnaryOperator)"](b => b.researchStack(Item.of('gtceu:advanced_smd_resistor')).EUt(GTValues.VA[GTValues.IV]).duration(420))

    event.recipes.gtceu.assembly_line("smd_quant_4")
    .itemInputs("4x gtceu:advanced_smd_capacitor","4x gtceu:cloudiron_ring","32x gtceu:fine_aerogem_wire")
    .itemOutputs("kubejs:quant_chip_4")
    .inputFluids([Fluid.of("gtceu:polycaprolactam",1440),Fluid.of("gtceu:tungsten_carbide",500),Fluid.of("gtceu:iridium",250)])
    .duration(280)
    .EUt(GTValues.VA[GTValues.LuV])
    ["scannerResearch(java.util.function.UnaryOperator)"](b => b.researchStack(Item.of('gtceu:advanced_smd_capacitor')).EUt(GTValues.VA[GTValues.IV]).duration(420))
    
    event.recipes.gtceu.assembly_line("smd_quant_5")
    .itemInputs('4x gtceu:advanced_smd_diode','16x gtceu:aerogem_foil','16x gtceu:nimbusite_foil')
    .itemOutputs('kubejs:quant_chip_5')
    .inputFluids([Fluid.of("gtceu:polycaprolactam",1440),Fluid.of("gtceu:tungsten_carbide",500),Fluid.of("gtceu:iridium",250)])
    .duration(280)
    .EUt(GTValues.VA[GTValues.LuV])
    ["scannerResearch(java.util.function.UnaryOperator)"](b => b.researchStack(Item.of('gtceu:advanced_smd_diode')).EUt(GTValues.VA[GTValues.IV]).duration(420))
})