ServerEvents.recipes(event => {
// Superclusters - Recipes
    event.recipes.gtceu.advanced_circuit_manufacturer("supercluster_asoc")
    .itemInputs("16x gtceu:advanced_soc","64x kubejs:super_seperator","64x gtceu:indium_tin_barium_titanium_cuprate_single_wire","128x gtceu:fine_platinum_wire","64x gtceu:electrum_foil")
    .inputFluids([Fluid.of("gtceu:cryotheum",12000),Fluid.of("gtceu:helium_plasma",10000)])
    .itemOutputs("kubejs:superclust_5")
    .notConsumable("gtceu:luv_emitter")
    .EUt(GTValues.VA[GTValues.LuV]).duration(1000).circuit(1)
    .dimension("ad_astra:earth_orbit")

    event.recipes.gtceu.advanced_circuit_manufacturer("supercluster_asoc_cwu")
    .itemInputs("16x gtceu:advanced_soc","64x kubejs:super_seperator","64x gtceu:indium_tin_barium_titanium_cuprate_single_wire","128x gtceu:fine_platinum_wire","64x gtceu:electrum_foil")
    .inputFluids([Fluid.of("gtceu:cryotheum",12000),Fluid.of("gtceu:helium_plasma",10000)])
    .itemOutputs("kubejs:superclust_5")
    .EUt(GTValues.VA[GTValues.LuV]).duration(500).circuit(2).CWUt(8)
    .dimension("ad_astra:earth_orbit")

    event.recipes.gtceu.advanced_circuit_manufacturer("supercluster_uhpic")
    .itemInputs("16x gtceu:uhpic_chip","64x kubejs:super_seperator","64x gtceu:indium_tin_barium_titanium_cuprate_single_wire","128x gtceu:fine_platinum_wire","64x gtceu:electrum_foil")
    .inputFluids([Fluid.of("gtceu:cryotheum",12000),Fluid.of("gtceu:helium_plasma",10000)])
    .itemOutputs("kubejs:superclust_1")
    .notConsumable("gtceu:luv_emitter")
    .EUt(GTValues.VA[GTValues.LuV]).duration(1000).circuit(3)
    .dimension("ad_astra:earth_orbit")

    event.recipes.gtceu.advanced_circuit_manufacturer("supercluster_uhpic_cwu")
    .itemInputs("16x gtceu:uhpic_chip","64x kubejs:super_seperator","64x gtceu:indium_tin_barium_titanium_cuprate_single_wire","128x gtceu:fine_platinum_wire","64x gtceu:electrum_foil")
    .inputFluids([Fluid.of("gtceu:cryotheum",12000),Fluid.of("gtceu:helium_plasma",10000)])
    .itemOutputs("kubejs:superclust_1")
    .EUt(GTValues.VA[GTValues.LuV]).duration(500).circuit(4).CWUt(8)
    .dimension("ad_astra:earth_orbit")

    event.recipes.gtceu.advanced_circuit_manufacturer("supercluster_hpic")
    .itemInputs("16x gtceu:hpic_chip","64x kubejs:super_seperator","64x gtceu:indium_tin_barium_titanium_cuprate_single_wire","128x gtceu:fine_platinum_wire","64x gtceu:electrum_foil")
    .inputFluids([Fluid.of("gtceu:cryotheum",8000),Fluid.of("gtceu:helium_plasma",10000)])
    .itemOutputs("kubejs:superclust_2")
    .notConsumable("gtceu:luv_emitter")
    .EUt(GTValues.VA[GTValues.LuV]).duration(1000).circuit(1)
    .dimension("ad_astra:earth_orbit")

    event.recipes.gtceu.advanced_circuit_manufacturer("supercluster_hpic_cwu")
    .itemInputs("16x gtceu:hpic_chip","64x kubejs:super_seperator","64x gtceu:indium_tin_barium_titanium_cuprate_single_wire","128x gtceu:fine_platinum_wire","64x gtceu:electrum_foil")
    .inputFluids([Fluid.of("gtceu:cryotheum",5000),Fluid.of("gtceu:helium_plasma",10000)])
    .itemOutputs("kubejs:superclust_2")
    .EUt(GTValues.VA[GTValues.LuV]).duration(500).circuit(2).CWUt(8)
    .dimension("ad_astra:earth_orbit")

    event.recipes.gtceu.advanced_circuit_manufacturer("supercluster_rhpcc")
    .itemInputs("16x kubejs:rhpcc_chip","64x kubejs:super_seperator","64x gtceu:indium_tin_barium_titanium_cuprate_single_wire","128x gtceu:fine_platinum_wire","64x gtceu:electrum_foil")
    .inputFluids([Fluid.of("gtceu:cryotheum",12000),Fluid.of("gtceu:helium_plasma",10000)])
    .itemOutputs("kubejs:superclust_3")
    .notConsumable("gtceu:luv_emitter")
    .EUt(GTValues.VA[GTValues.LuV]).duration(1000).circuit(1)
    .dimension("ad_astra:earth_orbit")

    event.recipes.gtceu.advanced_circuit_manufacturer("supercluster_rhpcc_cwu")
    .itemInputs("16x kubejs:rhpcc_chip","64x kubejs:super_seperator","64x gtceu:indium_tin_barium_titanium_cuprate_single_wire","128x gtceu:fine_platinum_wire","64x gtceu:electrum_foil")
    .inputFluids([Fluid.of("gtceu:cryotheum",8000),Fluid.of("gtceu:helium_plasma",10000)])
    .itemOutputs("kubejs:superclust_3")
    .EUt(GTValues.VA[GTValues.LuV]).duration(500).circuit(2).CWUt(8)
    .dimension("ad_astra:earth_orbit")

    event.recipes.gtceu.advanced_circuit_manufacturer("supercluster_ltmc")
    .itemInputs("16x kubejs:ltmc_chip","64x kubejs:super_seperator","64x gtceu:indium_tin_barium_titanium_cuprate_single_wire","128x gtceu:fine_platinum_wire","64x gtceu:electrum_foil")
    .inputFluids([Fluid.of("gtceu:cryotheum",15000),Fluid.of("gtceu:helium_plasma",10000)])
    .itemOutputs("kubejs:superclust_4")
    .notConsumable("gtceu:luv_emitter")
    .EUt(GTValues.VA[GTValues.LuV]).duration(1000).circuit(1)
    .dimension("ad_astra:earth_orbit")

    event.recipes.gtceu.advanced_circuit_manufacturer("supercluster_ltmc_cwu")
    .itemInputs("16x kubejs:ltmc_chip","64x kubejs:super_seperator","64x gtceu:indium_tin_barium_titanium_cuprate_single_wire","128x gtceu:fine_platinum_wire","64x gtceu:electrum_foil")
    .inputFluids([Fluid.of("gtceu:cryotheum",10000),Fluid.of("gtceu:helium_plasma",10000)])
    .itemOutputs("kubejs:superclust_4")
    .EUt(GTValues.VA[GTValues.LuV]).duration(500).circuit(2).CWUt(8)
    .dimension("ad_astra:earth_orbit")

    event.recipes.gtceu.advanced_circuit_manufacturer("supercluster_soc")
    .itemInputs("16x gtceu:soc","64x kubejs:super_seperator","64x gtceu:indium_tin_barium_titanium_cuprate_single_wire","128x gtceu:fine_platinum_wire","64x gtceu:electrum_foil")
    .inputFluids([Fluid.of("gtceu:cryotheum",10000),Fluid.of("gtceu:helium_plasma",10000)])
    .itemOutputs("kubejs:superclust_6")
    .notConsumable("gtceu:luv_emitter")
    .EUt(GTValues.VA[GTValues.LuV]).duration(1000).circuit(1)
    .dimension("ad_astra:earth_orbit")

    event.recipes.gtceu.advanced_circuit_manufacturer("supercluster_soc_cwu")
    .itemInputs("16x gtceu:soc","64x kubejs:super_seperator","64x gtceu:indium_tin_barium_titanium_cuprate_single_wire","128x gtceu:fine_platinum_wire","64x gtceu:electrum_foil")
    .inputFluids([Fluid.of("gtceu:cryotheum",5000),Fluid.of("gtceu:helium_plasma",10000)])
    .itemOutputs("kubejs:superclust_6")
    .EUt(GTValues.VA[GTValues.LuV]).duration(500).circuit(2).CWUt(8)
    .dimension("ad_astra:earth_orbit")

    event.recipes.gtceu.advanced_circuit_manufacturer("supercluster_qubit")
    .itemInputs("16x gtceu:qbit_cpu_chip","64x kubejs:super_seperator","64x gtceu:indium_tin_barium_titanium_cuprate_single_wire","128x gtceu:fine_platinum_wire","64x gtceu:electrum_foil")
    .inputFluids([Fluid.of("gtceu:cryotheum",15000),Fluid.of("gtceu:helium_plasma",10000)])
    .itemOutputs("kubejs:superclust_7")
    .notConsumable("gtceu:luv_emitter")
    .EUt(GTValues.VA[GTValues.LuV]).duration(1000).circuit(1)
    .dimension("ad_astra:earth_orbit")

    event.recipes.gtceu.advanced_circuit_manufacturer("supercluster_qubit_cwu")
    .itemInputs("16x gtceu:qbit_cpu_chip","64x kubejs:super_seperator","64x gtceu:indium_tin_barium_titanium_cuprate_single_wire","128x gtceu:fine_platinum_wire","64x gtceu:electrum_foil")
    .inputFluids([Fluid.of("gtceu:cryotheum",12000),Fluid.of("gtceu:helium_plasma",10000)])
    .itemOutputs("kubejs:superclust_7")
    .EUt(GTValues.VA[GTValues.LuV]).duration(500).circuit(2).CWUt(8)
    .dimension("ad_astra:earth_orbit")

    // Spacer
    event.recipes.gtceu.advanced_circuit_manufacturer("spacer_1")
    .itemInputs("4x gtceu:indium_tin_barium_titanium_cuprate_single_wire","32x kubejs:certus_quartz_fine_fiber","64x gtceu:electrum_foil","64x gtceu:fine_zephyrite_wire")
    .itemOutputs("4x kubejs:super_seperator")
    .inputFluids([Fluid.of("gtceu:cryotheum",6000),Fluid.of("gtceu:polycaprolactam",1500)])
    .EUt(GTValues.VA[GTValues.EV]).duration(100).circuit(1)
    .dimension("ad_astra:earth_orbit")

    event.recipes.gtceu.advanced_circuit_manufacturer("spacer_2")
    .itemInputs("2x gtceu:uranium_rhodium_dinaquadide_single_wire","16x gtceu:fine_europium_wire")
    .itemOutputs("16x kubejs:super_seperator")
    .inputFluids([Fluid.of("gtceu:cryotheum",4000),Fluid.of("gtceu:polycaprolactam",800)])
    .EUt(GTValues.VA[GTValues.LuV]).duration(200).circuit(2)
    .dimension("ad_astra:earth_orbit")

    event.recipes.gtceu.advanced_circuit_manufacturer("spacer_3")
    .itemInputs("gtceu:tritanium_single_wire","8x gtceu:fine_americium_wire")
    .itemOutputs("32x kubejs:super_seperator")
    .inputFluids([Fluid.of("gtceu:cryotheum",2000),Fluid.of("gtceu:polycaprolactam",144)])
    .EUt(GTValues.VA[GTValues.ZPM]).duration(300).circuit(3)
    .dimension("ad_astra:earth_orbit")
})