GTCEuStartupEvents.registry("gtceu:dimension_marker", event => {
// Ad Astra dimensions
    event.create("ad_astra:moon")
        .iconSupplier(() => Item.of("ad_astra:moon_globe").getItem())
        .tier(0)
        .overrideName("Moon")
    event.create("ad_astra:moon_orbit")
        .iconSupplier(() => Item.of("ad_astra:moon_globe").getItem())
        .tier(0)
        .overrideName("Moon Orbit")
    event.create("ad_astra:mars")
        .iconSupplier(() => Item.of("ad_astra:mars_globe").getItem())
        .tier(0)
        .overrideName("Mars")
    event.create("ad_astra:mercury")
        .iconSupplier(() => Item.of("ad_astra:mercury_globe").getItem())
        .tier(0)
        .overrideName("Mercury")
    event.create("ad_astra:venus")
        .iconSupplier(() => Item.of("ad_astra:venus_globe").getItem())
        .tier(0)
        .overrideName("Venus")
    event.create("ad_astra:glacio")
        .iconSupplier(() => Item.of("ad_astra:glacio_globe").getItem())
        .tier(0)
        .overrideName("Glacio")

    event.create("ad_astra:earth_orbit")
        .iconSupplier(() => Item.of("ad_astra:earth_globe").getItem())
        .tier(0)
        .overrideName("Earth Orbit")
})

// Add new ones here if needed for any other dimensions, thanks to Phoenixvine I found this "!"