GTCEuStartupEvents.registry('gtceu:material', event => {
        event.create('alumite_rocket_fuel')
        .fluid()
        .color(0x420326)
        event.create('nether_juice')
        .fluid()
        .color(0x420326)
        event.create('distilled_nether_juice')
        .fluid()
        .color(0x420326)
        event.create('impure_crude_oil')
        .fluid()
        .color(0x420326)
        event.create('heavy_impure_crude_oil')
        .fluid()
        .color(0x420326)
        event.create('pure_silicon_crystal_slurry')
        .fluid()
        .color(0x420326)
        event.create('silicon_slurry')
        .fluid()
        .color(0x420326)
        event.create('tritium_alcoholate')
        .fluid()
        .color(0x420326)
        event.create('organosilicate')
        .fluid()
        .color(0x420326)
        event.create('trichlorosaline')
        .fluid()
        .color(0x420326)
        event.create('pure_trichlorosaline')
        .fluid()
        .color(0x420326)
        event.create('hydrogen_peroxide')
        .fluid()
        .color(0x420326)
        event.create('hydrogen_chloride')
        .fluid()
        .color(0x420326)
        event.create('diazonaphthoquinone')
        .fluid()
        .color(0x420326)
        event.create('aether_air')
        .gas()
        .color(0x420326)
        event.create('compressed_aether_air')
        .gas()
        .color(0x420326)
        event.create('super_compressed_aether_air')
        .plasma()
        .color(0x420326)

        // Titanium Line
        event.create('bauxite_hydroxide')
        .fluid()
        .color(0x420326)
        event.create('neutral_bauxite_hydroxide')
        .fluid()
        .color(0x420326)
        event.create('hollow_earth_filtrate')
        .fluid()
        .color(0x420326)
        event.create('volatile_alumino_mix')
        .fluid()
        .color(0x420326)
        event.create('thermo_shock_residue')
        .fluid()
        .color(0x420326)
        event.create('crystal_titanium_rich_compound')
        .fluid()
        .color(0x420326)

        // Quantum Line
        event.create("methyl_chloride")
        .fluid()
        .color(0x420326)
        event.create("tetramethylammonium_hydroxide")
        .fluid()
        .color(0x420326)
        event.create("trimethylamine")
        .fluid()
        .color(0x420326)
        event.create("cleaning_fluid") // placeholder name
        .fluid()
        .color(0x420326)
        event.create("indium_antimonide")
        .dust()
        .color(0x420326)
        event.create("radon_xenotrihydride")
        .fluid()
        .color(0x420326)

        // Nether Star Line & Compressor
        event.create("compressed_hydrogen")
        .gas()
        .color(0x420326)
        event.create("super_compressed_hydrogen")
        .plasma()
        .color(0x420326)
        event.create("compressed_krypton")
        .gas()
        .color(0x420326)
        event.create("super_compressed_krypton")
        .plasma()
        .color(0x420326)
        event.create("solarium")
        .fluid()
        .color(0x420326)
        event.create("compressed_solarium")
        .gas()
        .color(0x420326)
        event.create("super_compressed_solarium")
        .plasma()
        .color(0x420326)
        event.create("liquid_nether_star")
        .fluid()
        .color(0x420326)

        // LUV Stuff
        event.create('high_grade_silicon')
        .dust()
        .color(0x7D2DDB)
        .flags(GTMaterialFlags.FORCE_GENERATE_BLOCK)
        event.create('high_grade_solder')
        .liquid()
        .color(0x7D2DDB)
        event.create('naqatrite')
        .liquid()
        .ingot()
        .flags(GTMaterialFlags.GENERATE_PLATE,GTMaterialFlags.GENERATE_FOIL)
        .color(0x7D2DDB)

        // Misc.
        event.create('cryotheum')
        .liquid()
        .color(0x7D2DDB)

        // Fusion Segment
        // Fusion Fuel - (pls help me)
        event.create('gallium_pl')
        .plasma()
        .color(0x7D2DDB)
        event.create('osmium_pl')
        .plasma()
        .color(0x7D2DDB)
        event.create('iridium_pl')
        .plasma()
        .color(0x7D2DDB)
        event.create('yttrium_pl')
        .plasma()
        .color(0x7D2DDB)
        event.create('cobalt_pl')
        .plasma()
        .color(0x7D2DDB)
        event.create('tungsten_pl')
        .plasma()
        .color(0x7D2DDB)
        event.create('samarium_pl')
        .plasma()
        .color(0x7D2DDB)
        event.create('vanadium_pl')
        .plasma()
        .color(0x7D2DDB)

        // Fuel Combination 1-4
        event.create('gallosium')
        .plasma()
        .color(0x7D2DDB)
        event.create('iridyne')
        .plasma()
        .color(0x7D2DDB)
        event.create('cobalten')
        .plasma()
        .color(0x7D2DDB)
        event.create('samaradium')
        .plasma()
        .color(0x7D2DDB)

        // Fuel Combination
        event.create('givs_13_fuel')
        .plasma()
        .color(0x7D2DDB)

        // ZPM
        event.create('silquadria')
        .plasma()
        .color(0x7D2DDB)
        event.create('silquadria_fuel')
        .plasma()
        .color(0x7D2DDB)
        event.create('spent_silquadria')
        .plasma()
        .color(0x7D2DDB)
        event.create('actinex')
        .liquid()
        .color(0x7D2DDB)
        event.create('supercooled_cryotheum')
        .gas()
        .color(0x7D2DDB)
        event.create('supercooled_ice')
        .gas()
        .color(0x7D2DDB)
        event.create('stellaric_neutronium')
        .liquid()
        .color(0x7D2DDB)
        event.create('unstable_draconium')
        .liquid()
        .color(0x7D2DDB)
        event.create('draconium')
        .liquid().ingot()
        .flags(GTMaterialFlags.GENERATE_DENSE)
        .color(0x7D2DDB)
        event.create('unstable_neutronium')
        .liquid()
        .color(0x7D2DDB)
        event.create('quantum_star')
        .liquid()
        .color(0xFFFFFF)
        event.create('subatomic_pattering_gel')
        .liquid()
        .color(0x7D2DDB)
        event.create('triazirinyl')
        .liquid()
        .color(0x7D2DDB)
        event.create('petroxide_suspension')
        .liquid()
        .color(0x7D2DDB)
        event.create('neon_cadmide')
        .liquid()
        .flags(GTMaterialFlags.GENERATE_BOLT_SCREW,GTMaterialFlags.GENERATE_FINE_WIRE,GTMaterialFlags.GENERATE_PLATE,GTMaterialFlags.GENERATE_FOIL)
        .color(0xFF3FAF)
        event.create('proton_fluid')
        .liquid()
        .color(0x7D2DDB)
        event.create('excited_proton_fluid')
        .gas()
        .color(0x7D2DDB)




        // ZPM BioChemical Line
        event.create('deuterium_oxide')
        .gas()
        .color(0x7D2DDB)
        event.create('xenon_oxide')
        .gas()
        .color(0x7D2DDB)
        event.create('decay_naquadric_acid')
        .liquid()
        .color(0x7D2DDB)
        event.create('decaying_protein')
        .liquid()
        .color(0x7D2DDB)

        event.create('glucose_solution')
        .liquid()
        .color(0x7D2DDB)
        event.create('saline_solution')
        .liquid()
        .color(0x7D2DDB)
        event.create('blood_plasma')
        .liquid()
        .color(0x7D2DDB)
        event.create('blood_cells')
        .liquid()
        .color(0x7D2DDB)
        event.create('plasma_enriched_blood_cells')
        .liquid()
        .color(0x7D2DDB)
        event.create('protein_slurry')
        .liquid()
        .color(0x7D2DDB)
        event.create('high_purity_protein')
        .liquid()
        .color(0x7D2DDB)
        event.create('nutrient_medium')
        .liquid()
        .color(0x7D2DDB)
        event.create('blood_devrived_genetic_material')
        .liquid()
        .color(0x7D2DDB)
        event.create('mutated_bacterial_sludge')
        .liquid()
        .color(0x7D2DDB)
        event.create('purified_generic_mass')
        .liquid()
        .color(0x7D2DDB)
        event.create('stabilized_growth_medium')
        .liquid()
        .color(0x7D2DDB)
        event.create('cryogenic_blood_cells')
        .liquid()
        .color(0x7D2DDB)
        event.create('hematogenic_catalyst')
        .liquid()
        .color(0x7D2DDB)
        event.create('beta_cell_cluster')
        .liquid()
        .color(0x7D2DDB)
        event.create('recombinated_dna_strands')
        .liquid()
        .color(0x7D2DDB)
        event.create('proto_cell_cluster')
        .liquid()
        .color(0x7D2DDB)
        event.create('dna_fragments')
        .liquid()
        .color(0x7D2DDB)
        event.create('rapid_replicate_protein_cells')
        .liquid()
        .color(0x7D2DDB)
        event.create('evolved_bacterial_culture')
        .liquid()
        .color(0x7D2DDB)


        // Repulsor - Naqline
        event.create('naquadic_combust_agent_1')
        .liquid()
        .color(0x7D2DDB)
        event.create('naquadic_combust_agent_2')
        .gas()
        .color(0x7D2DDB)
        event.create('supercooled_naquadic_fuel')
        .gas()
        .color(0x7D2DDB)
        event.create('cryocracked_naquadic_fuel_mix')
        .gas()
        .color(0x7D2DDB)
        event.create('fuel_mixture_naquadic_1')
        .liquid()
        .color(0x7D2DDB)
        event.create('ammonium_lithium_nitrate_1')
        .liquid()
        .color(0x7D2DDB)
        event.create('naquadic_fuel_mix_base')
        .liquid()
        .color(0x7D2DDB)
        event.create('cobalt_mang_sulfuric_acid')
        .liquid()
        .color(0x7D2DDB)
        event.create('kryptoxene')
        .gas()
        .color(0x7D2DDB)
        event.create('naquadrolene')
        .liquid()
        .color(0x7D2DDB)
        event.create('superheated_steam')
        .gas()
        .color(0x7D2DDB)
        event.create('supercritical_steam')
        .plasma()
        .color(0x7D2DDB)

        // Ore Synthetic Chamber (OSD)
        event.create('acetylene')
        .liquid()
        .color(0x7D2DDB)
        event.create('propylene')
        .liquid()
        .color(0x7D2DDB)
        event.create('polycyclic_aromatic_hydrocarbon')
        .liquid()
        .color(0x7D2DDB)
        event.create('acrylic_acid')
        .liquid()
        .color(0x7D2DDB)
        event.create('polyromatic_fluid')
        .liquid()
        .color(0x7D2DDB)
        event.create('crystal_formic_aromatic_hydrocarbonized_acid') // Crystal-Formic Aromatic Hydrocarbonized Acid
        .liquid()
        .color(0x7D2DDB)

})


GTCEuStartupEvents.registry('gtceu:material', event => {
  event.create('nitrogen_feedstock')
    .fluid()
    .color(0x9ec9ff); // just color, no fluidTemp

  event.create('azirine_feedstock')
    .fluid()
    .color(0xffa500);
});

 




