StartupEvents.registry('item', e => {
    e.create("rose_quartz_plate").displayName("Rose Quartz Plate")
    e.create("certus_quartz_fine_fiber").displayName("Certus Quartz Fine Fiber")
    e.create("moon_turf").displayName("Moon Turf")
    e.create("cord_card_1").displayName("Coordination Card T1")
    e.create("cord_card_2").displayName("Coordination Card T2")
    e.create("cord_card_3").displayName("Coordination Card T3")
    e.create("cord_card_4").displayName("Coordination Card T4")
    e.create("sat_1").displayName("Satellite T1")
    e.create("sat_2").displayName("Satellite T2")
    e.create("sat_3").displayName("Satellite T3")
    e.create("energized_ingot_of_silicon").displayName("Energized Silicon Ingot")
    e.create("crystal_cpu").displayName("Crystal CPU")
    e.create("super_seperator").displayName("Interconnecter")
    e.create("draconic_reflector").displayName("Draconic Reflector")


    e.create("lv_stator").displayName("LV Stator")
    e.create("mv_stator").displayName("MV Stator")
    e.create("hv_stator").displayName("HV Stator")
    e.create("ev_stator").displayName("EV Stator")
    e.create("iv_stator").displayName("IV Stator")
    e.create("luv_stator").displayName("LUV Stator")
    e.create("zpm_stator").displayName("ZPM Stator")
    e.create("uv_stator").displayName("UV Stator")

    e.create("lv_rotor").displayName("LV Rotor")
    e.create("mv_rotor").displayName("MV Rotor")
    e.create("hv_rotor").displayName("HV Rotor")
    e.create("ev_rotor").displayName("EV Rotor")
    e.create("iv_rotor").displayName("IV Rotor")
    e.create("luv_rotor").displayName("LUV Rotor")
    e.create("zpm_rotor").displayName("ZPM Rotor")
    e.create("uv_rotor").displayName("UV Rotor")


    e.create("ae_logic_wafer").displayName("Logic Processor Wafer")
    e.create("ae_engineering_wafer").displayName("Engineering Processor Wafer")
    e.create("ae_calculation_wafer").displayName("Calculation Processor Wafer")
    e.create("ae_accu_wafer").displayName("Accumulation Processor Wafer")
    e.create("ae_quantum_wafer").displayName("Quantum Processor Wafer")

    // ZPM BioChemical Line
    e.create("culture_1")
    e.create("culture_2")
    e.create("evo_culture_1")
    e.create("cell_1")
    e.create("cell_2")

    // Circuits Rework (had a idea to make the pack unique)
    e.create("t1_circuit_lv").displayName("Electronic Circuit")
    e.create("t1_circuit_mv").displayName("Integrated Circuit")
    e.create("t1_circuit_hv").displayName("Microprocessor")
    e.create("t1_circuit_ev").displayName("Nano Processor")
    e.create("t1_circuit_iv").displayName("Quantum Supercomputer")
    e.create("t1_circuit_luv").displayName("Superpositioned Crystal Mainframe")
    e.create("t1_circuit_zpm").displayName("Superpositioned Biotine Mainframe")
    e.create("biotine_supercomputer").displayName("Superpositioned Biotine Supercluster")
    e.create("t1_circuit_uv").displayName("Optical Photonic Superpositioned Processor")
    e.create("t1_circuit_uhv").displayName("Optical Photonic Mainframe Supercluster")

    ////////////////////////////

    e.create("compressed_plant_ball").displayName("Compressed Plant Ball")
    e.create("purified_biomass_pallet").displayName("Purified Biomass")

    e.create("prepared_silicon_wafer").displayName("Prepared Silicon Wafer")
    e.create("prepared_phosphorus_wafer").displayName("Prepared Phosphorus Wafer")
    e.create("prepared_naquadah_wafer").displayName("Prepared Naquadah Wafer")
    e.create("prepared_neutronium_wafer").displayName("Prepared Neutronium Wafer")
    e.create("prepared_nano_wafer").displayName("Prepared Nano Wafer")

    e.create("dirty_silicon_wafer").displayName("Contaminated Silicon Wafer")
    e.create("dirty_phosphorus_wafer").displayName("Contaminated Phosphorus Wafer")
    e.create("dirty_naquadah_wafer").displayName("Contaminated Naquadah Wafer")
    e.create("dirty_neutronium_wafer").displayName("Contaminated Neutronium Wafer")
    e.create("dirty_processed_wafer").displayName("Contaminated Processed Wafer")
    e.create("dirty_nano_wafer").displayName("Contaminated Nano Wafer")

    e.create("foub").displayName("Wafer Foub")
    e.create("ltmc_chip").displayName("LTMC Chip")
    e.create("ltmc_wafer").displayName("LTMC Wafer")
    e.create("ctc_wafer").displayName("CTC Wafer")
    e.create("cmc_wafer").displayName("CMC Wafer")
    e.create("rhpcc_chip").displayName("High Power CPU Chip")
    e.create("ctc_chip").displayName("Advanced Timing Chip")
    e.create("cmc_chip").displayName("Advanced Memory Controller")
    e.create("prep_n_wafer").displayName("Prepared Nano Wafer")
    e.create("nwm").displayName("Nano Wafer Mask")
    e.create("ancw").displayName("Advanced Nano CPU Wafer")
    e.create("qwm").displayName("Quantum Wafer Mask")
    e.create("prep_q_wafer").displayName("Prepared Quantum Wafer")
    e.create("hahdic_wafer").displayName("Hahdic Wafer")
    e.create("hahdic_chip").displayName("Hahdic Chip")
    e.create("graphene_rod").displayName("Graphene Rod")
    e.create("inert_enriched_rod").displayName("Inert-Gas Enriched Carbon Fuel Rod")
    e.create("rhodium_palladium_reflector").displayName("Rhodium Palladium Coated Solar Reflector")
    e.create("tungsten_laser_focus").displayName("Tungstensteel Laser Focus")
    e.create("quant_chip_1").displayName("Quantaline SMD Transistor")
    e.create("quant_chip_2").displayName("Quantaline SMD Inductor")
    e.create("quant_chip_3").displayName("Quantaline SMD Resistor")
    e.create("quant_chip_4").displayName("Quantaline SMD Capacitor")
    e.create("quant_chip_5").displayName("Quantaline SMD Diode")
    e.create("superclust_1").displayName("UHPIC Chip Supercluster")
    e.create("superclust_2").displayName("HPIC Chip Supercluster")
    e.create("superclust_3").displayName("HPCC Chip Supercluster")
    e.create("superclust_4").displayName("LTMC Chip Supercluster")
    e.create("superclust_5").displayName("ASoC Chip Supercluster")
    e.create("superclust_6").displayName("SoC Chip Supercluster")
    e.create("superclust_7").displayName("Qubit CPU Chip Supercluster")
})

StartupEvents.registry('block', event => {
    event.create("energized_block_of_silicon").displayName("Energized Block of Silicon")
    event.create("sky_stone_block").displayName("Sky Stone Block")

    event.create("superconducting_magnet").displayName("placeholder Magnet")
    event.create("superconducting_anti_magnet").displayName("Placeholder Magnet")

    event.create('reactor_coil_block', 'gtceu:coil')
        .temperature(4500)
        .level(4)
        .energyDiscount(2)
        .tier(5)
        .texture('kubejs:block/coils/reactor_coil')
        .hardness(5)
        .requiresTool(true)
        .soundType(SoundType.NETHERITE_BLOCK)
        .tagBlock('forge:mineable/wrench')  
    // when somebody finds out how to do the texture stuff, let me know, I have no idea

})

StartupEvents.registry('fluid', e => {
    e.create("bacterial_sludge")
    .displayName("Liquid Artifical Bacteria Base")
    .thickTexture(0xFF0000)
    .bucketColor(0xFF33FF)

    e.create("artifical_coolant_synthetic_base")
    .displayName("Artifical Coolant Base")
    .thickTexture(0xFF0000)
    .bucketColor(0xFF33FF) 
})

