GTCEuStartupEvents.registry('gtceu:material', event => {
    event.create('sky_stone')
        .ore()
        .dust()
        .liquid()
        .blastTemp(2700, 'mid', GTValues.VA[GTValues.EV], 600)
        .components("2x steel","tungsten")
        .color(0x7D2DDB)

        event.create('dilithium')
        .ore(2, 3)
        .dust()
        .color(0x7D2DDB).iconSet(GTMaterialIconSet.QUARTZ)

        // LUV stuff
        event.create('zephyrite')
        .ore()
        .ingot()
        .dust()
        .flags(GTMaterialFlags.GENERATE_FOIL,GTMaterialFlags.GENERATE_FINE_WIRE)
        .blastTemp(4500) 
        .color(0x7D2DDB)

        event.create('aerogem')
        .ore()
        .ingot()
        .dust()
        .flags(GTMaterialFlags.GENERATE_FINE_WIRE)
        .blastTemp(4500)
        .color(0x7D2DDB)

        event.create('cloudiron')
        .ore()
        .ingot()
        .dust()
        .flags(GTMaterialFlags.GENERATE_RING,GTMaterialFlags.GENERATE_DENSE)
        .blastTemp(4500)
        .color(0x7D2DDB)

        event.create('nimbusite')
        .ore()
        .ingot()
        .dust()
        .flags(GTMaterialFlags.GENERATE_FOIL,GTMaterialFlags.GENERATE_FINE_WIRE)
        .blastTemp(4500)
        .color(0x7D2DDB)

        event.create('halocite')
        .ore()
        .ingot()
        .dust()
        .flags(GTMaterialFlags.GENERATE_FOIL,GTMaterialFlags.GENERATE_DENSE)
        .blastTemp(4500)
        .color(0x7D2DDB)
})